---
abstract: 'perl bind for Qless job queueing system'
author:
  - 'qless, qless-py and qless-core - SEOmoz'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Qless
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Class::Load: 0
  File::ShareDir: 0
  JSON::XS: 0
  Redis: 0
  Time::HiRes: 0
version: 0.01
